// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ActorMapping } from '../nmeshed/actor-mapping.js';


export class ActorRegistry {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ActorRegistry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsActorRegistry(bb:flatbuffers.ByteBuffer, obj?:ActorRegistry):ActorRegistry {
  return (obj || new ActorRegistry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsActorRegistry(bb:flatbuffers.ByteBuffer, obj?:ActorRegistry):ActorRegistry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ActorRegistry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

mappings(index: number, obj?:ActorMapping):ActorMapping|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ActorMapping()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

mappingsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startActorRegistry(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMappings(builder:flatbuffers.Builder, mappingsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, mappingsOffset, 0);
}

static createMappingsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMappingsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endActorRegistry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createActorRegistry(builder:flatbuffers.Builder, mappingsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ActorRegistry.startActorRegistry(builder);
  ActorRegistry.addMappings(builder, mappingsOffset);
  return ActorRegistry.endActorRegistry(builder);
}
}
