// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ActorMapping {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ActorMapping {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsActorMapping(bb:flatbuffers.ByteBuffer, obj?:ActorMapping):ActorMapping {
  return (obj || new ActorMapping()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsActorMapping(bb:flatbuffers.ByteBuffer, obj?:ActorMapping):ActorMapping {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ActorMapping()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

idx():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startActorMapping(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addIdx(builder:flatbuffers.Builder, idx:number) {
  builder.addFieldInt32(0, idx, 0);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, idOffset, 0);
}

static endActorMapping(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createActorMapping(builder:flatbuffers.Builder, idx:number, idOffset:flatbuffers.Offset):flatbuffers.Offset {
  ActorMapping.startActorMapping(builder);
  ActorMapping.addIdx(builder, idx);
  ActorMapping.addId(builder, idOffset);
  return ActorMapping.endActorMapping(builder);
}
}
