// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Candidate {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Candidate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCandidate(bb:flatbuffers.ByteBuffer, obj?:Candidate):Candidate {
  return (obj || new Candidate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCandidate(bb:flatbuffers.ByteBuffer, obj?:Candidate):Candidate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Candidate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

candidate():string|null
candidate(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
candidate(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sdpMid():string|null
sdpMid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sdpMid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sdpMLineIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startCandidate(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addCandidate(builder:flatbuffers.Builder, candidateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, candidateOffset, 0);
}

static addSdpMid(builder:flatbuffers.Builder, sdpMidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, sdpMidOffset, 0);
}

static addSdpMLineIndex(builder:flatbuffers.Builder, sdpMLineIndex:number) {
  builder.addFieldInt32(2, sdpMLineIndex, 0);
}

static endCandidate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCandidate(builder:flatbuffers.Builder, candidateOffset:flatbuffers.Offset, sdpMidOffset:flatbuffers.Offset, sdpMLineIndex:number):flatbuffers.Offset {
  Candidate.startCandidate(builder);
  Candidate.addCandidate(builder, candidateOffset);
  Candidate.addSdpMid(builder, sdpMidOffset);
  Candidate.addSdpMLineIndex(builder, sdpMLineIndex);
  return Candidate.endCandidate(builder);
}
}
