// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Hlc, HlcT } from '../nmeshed/hlc.js';


export class CompareAndSwap implements flatbuffers.IUnpackableObject<CompareAndSwapT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CompareAndSwap {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCompareAndSwap(bb:flatbuffers.ByteBuffer, obj?:CompareAndSwap):CompareAndSwap {
  return (obj || new CompareAndSwap()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCompareAndSwap(bb:flatbuffers.ByteBuffer, obj?:CompareAndSwap):CompareAndSwap {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CompareAndSwap()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

expectedValue(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

expectedValueLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

expectedValueArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

newValue(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

newValueLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

newValueArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

actorId():string|null
actorId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
actorId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

timestamp(obj?:Hlc):Hlc|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Hlc()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startCompareAndSwap(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addExpectedValue(builder:flatbuffers.Builder, expectedValueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, expectedValueOffset, 0);
}

static createExpectedValueVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startExpectedValueVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addNewValue(builder:flatbuffers.Builder, newValueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, newValueOffset, 0);
}

static createNewValueVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startNewValueVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addActorId(builder:flatbuffers.Builder, actorIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, actorIdOffset, 0);
}

static addTimestamp(builder:flatbuffers.Builder, timestampOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, timestampOffset, 0);
}

static endCompareAndSwap(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): CompareAndSwapT {
  return new CompareAndSwapT(
    this.key(),
    this.bb!.createScalarList<number>(this.expectedValue.bind(this), this.expectedValueLength()),
    this.bb!.createScalarList<number>(this.newValue.bind(this), this.newValueLength()),
    this.actorId(),
    (this.timestamp() !== null ? this.timestamp()!.unpack() : null)
  );
}


unpackTo(_o: CompareAndSwapT): void {
  _o.key = this.key();
  _o.expectedValue = this.bb!.createScalarList<number>(this.expectedValue.bind(this), this.expectedValueLength());
  _o.newValue = this.bb!.createScalarList<number>(this.newValue.bind(this), this.newValueLength());
  _o.actorId = this.actorId();
  _o.timestamp = (this.timestamp() !== null ? this.timestamp()!.unpack() : null);
}
}

export class CompareAndSwapT implements flatbuffers.IGeneratedObject {
constructor(
  public key: string|Uint8Array|null = null,
  public expectedValue: (number)[] = [],
  public newValue: (number)[] = [],
  public actorId: string|Uint8Array|null = null,
  public timestamp: HlcT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const key = (this.key !== null ? builder.createString(this.key!) : 0);
  const expectedValue = CompareAndSwap.createExpectedValueVector(builder, this.expectedValue);
  const newValue = CompareAndSwap.createNewValueVector(builder, this.newValue);
  const actorId = (this.actorId !== null ? builder.createString(this.actorId!) : 0);

  CompareAndSwap.startCompareAndSwap(builder);
  CompareAndSwap.addKey(builder, key);
  CompareAndSwap.addExpectedValue(builder, expectedValue);
  CompareAndSwap.addNewValue(builder, newValue);
  CompareAndSwap.addActorId(builder, actorId);
  CompareAndSwap.addTimestamp(builder, (this.timestamp !== null ? this.timestamp!.pack(builder) : 0));

  return CompareAndSwap.endCompareAndSwap(builder);
}
}
