// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CompareAndSwap {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CompareAndSwap {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCompareAndSwap(bb:flatbuffers.ByteBuffer, obj?:CompareAndSwap):CompareAndSwap {
  return (obj || new CompareAndSwap()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCompareAndSwap(bb:flatbuffers.ByteBuffer, obj?:CompareAndSwap):CompareAndSwap {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CompareAndSwap()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

expectedValue(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

expectedValueLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

expectedValueArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

newValue(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

newValueLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

newValueArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

actorId():string|null
actorId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
actorId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

timestamp():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startCompareAndSwap(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addExpectedValue(builder:flatbuffers.Builder, expectedValueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, expectedValueOffset, 0);
}

static createExpectedValueVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startExpectedValueVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addNewValue(builder:flatbuffers.Builder, newValueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, newValueOffset, 0);
}

static createNewValueVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startNewValueVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addActorId(builder:flatbuffers.Builder, actorIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, actorIdOffset, 0);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:number) {
  builder.addFieldFloat64(4, timestamp, 0.0);
}

static endCompareAndSwap(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCompareAndSwap(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, expectedValueOffset:flatbuffers.Offset, newValueOffset:flatbuffers.Offset, actorIdOffset:flatbuffers.Offset, timestamp:number):flatbuffers.Offset {
  CompareAndSwap.startCompareAndSwap(builder);
  CompareAndSwap.addKey(builder, keyOffset);
  CompareAndSwap.addExpectedValue(builder, expectedValueOffset);
  CompareAndSwap.addNewValue(builder, newValueOffset);
  CompareAndSwap.addActorId(builder, actorIdOffset);
  CompareAndSwap.addTimestamp(builder, timestamp);
  return CompareAndSwap.endCompareAndSwap(builder);
}
}
