// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Hlc {
    bb: flatbuffers.ByteBuffer | null = null;
    bb_pos = 0;
    __init(i: number, bb: flatbuffers.ByteBuffer): Hlc {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }

    upper(): bigint {
        return this.bb!.readInt64(this.bb_pos);
    }

    lower(): bigint {
        return this.bb!.readInt64(this.bb_pos + 8);
    }

    static createHlc(builder: flatbuffers.Builder, upper: bigint, lower: bigint): flatbuffers.Offset {
        builder.prep(8, 16);
        builder.writeInt64(lower);
        builder.writeInt64(upper);
        return builder.offset();
    }

}
