// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class Join implements flatbuffers.IUnpackableObject<JoinT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Join {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsJoin(bb:flatbuffers.ByteBuffer, obj?:Join):Join {
  return (obj || new Join()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsJoin(bb:flatbuffers.ByteBuffer, obj?:Join):Join {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Join()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

workspaceId():string|null
workspaceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
workspaceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startJoin(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addWorkspaceId(builder:flatbuffers.Builder, workspaceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, workspaceIdOffset, 0);
}

static endJoin(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createJoin(builder:flatbuffers.Builder, workspaceIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  Join.startJoin(builder);
  Join.addWorkspaceId(builder, workspaceIdOffset);
  return Join.endJoin(builder);
}

unpack(): JoinT {
  return new JoinT(
    this.workspaceId()
  );
}


unpackTo(_o: JoinT): void {
  _o.workspaceId = this.workspaceId();
}
}

export class JoinT implements flatbuffers.IGeneratedObject {
constructor(
  public workspaceId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const workspaceId = (this.workspaceId !== null ? builder.createString(this.workspaceId!) : 0);

  return Join.createJoin(builder,
    workspaceId
  );
}
}
