// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MsgType {
  Unknown = 0,
  Op = 1,
  Sync = 2,
  Signal = 3,
  Init = 4,
  ActorRegistry = 5,
  ColumnarBatch = 6,
  CompareAndSwap = 7
}
