// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Offer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Offer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOffer(bb:flatbuffers.ByteBuffer, obj?:Offer):Offer {
  return (obj || new Offer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOffer(bb:flatbuffers.ByteBuffer, obj?:Offer):Offer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Offer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sdp():string|null
sdp(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sdp(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startOffer(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSdp(builder:flatbuffers.Builder, sdpOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sdpOffset, 0);
}

static endOffer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOffer(builder:flatbuffers.Builder, sdpOffset:flatbuffers.Offset):flatbuffers.Offset {
  Offer.startOffer(builder);
  Offer.addSdp(builder, sdpOffset);
  return Offer.endOffer(builder);
}
}
