// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class StateVectorEntry implements flatbuffers.IUnpackableObject<StateVectorEntryT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StateVectorEntry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStateVectorEntry(bb:flatbuffers.ByteBuffer, obj?:StateVectorEntry):StateVectorEntry {
  return (obj || new StateVectorEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStateVectorEntry(bb:flatbuffers.ByteBuffer, obj?:StateVectorEntry):StateVectorEntry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateVectorEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

peerId():string|null
peerId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
peerId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

seq():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startStateVectorEntry(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPeerId(builder:flatbuffers.Builder, peerIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, peerIdOffset, 0);
}

static addSeq(builder:flatbuffers.Builder, seq:bigint) {
  builder.addFieldInt64(1, seq, BigInt('0'));
}

static endStateVectorEntry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStateVectorEntry(builder:flatbuffers.Builder, peerIdOffset:flatbuffers.Offset, seq:bigint):flatbuffers.Offset {
  StateVectorEntry.startStateVectorEntry(builder);
  StateVectorEntry.addPeerId(builder, peerIdOffset);
  StateVectorEntry.addSeq(builder, seq);
  return StateVectorEntry.endStateVectorEntry(builder);
}

unpack(): StateVectorEntryT {
  return new StateVectorEntryT(
    this.peerId(),
    this.seq()
  );
}


unpackTo(_o: StateVectorEntryT): void {
  _o.peerId = this.peerId();
  _o.seq = this.seq();
}
}

export class StateVectorEntryT implements flatbuffers.IGeneratedObject {
constructor(
  public peerId: string|Uint8Array|null = null,
  public seq: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const peerId = (this.peerId !== null ? builder.createString(this.peerId!) : 0);

  return StateVectorEntry.createStateVectorEntry(builder,
    peerId,
    this.seq
  );
}
}
