// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { StateVectorEntry } from '../nmeshed/state-vector-entry.js';


export class SyncPacket {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SyncPacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSyncPacket(bb:flatbuffers.ByteBuffer, obj?:SyncPacket):SyncPacket {
  return (obj || new SyncPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSyncPacket(bb:flatbuffers.ByteBuffer, obj?:SyncPacket):SyncPacket {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SyncPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

stateVector(index: number, obj?:StateVectorEntry):StateVectorEntry|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new StateVectorEntry()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

stateVectorLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

snapshot(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

snapshotLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

snapshotArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

ackSeq():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startSyncPacket(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStateVector(builder:flatbuffers.Builder, stateVectorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stateVectorOffset, 0);
}

static createStateVectorVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStateVectorVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSnapshot(builder:flatbuffers.Builder, snapshotOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, snapshotOffset, 0);
}

static createSnapshotVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startSnapshotVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addAckSeq(builder:flatbuffers.Builder, ackSeq:bigint) {
  builder.addFieldInt64(2, ackSeq, BigInt('0'));
}

static endSyncPacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSyncPacket(builder:flatbuffers.Builder, stateVectorOffset:flatbuffers.Offset, snapshotOffset:flatbuffers.Offset, ackSeq:bigint):flatbuffers.Offset {
  SyncPacket.startSyncPacket(builder);
  SyncPacket.addStateVector(builder, stateVectorOffset);
  SyncPacket.addSnapshot(builder, snapshotOffset);
  SyncPacket.addAckSeq(builder, ackSeq);
  return SyncPacket.endSyncPacket(builder);
}
}
