// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class SyncRequest implements flatbuffers.IUnpackableObject<SyncRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SyncRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSyncRequest(bb:flatbuffers.ByteBuffer, obj?:SyncRequest):SyncRequest {
  return (obj || new SyncRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSyncRequest(bb:flatbuffers.ByteBuffer, obj?:SyncRequest):SyncRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SyncRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

workspaceId():string|null
workspaceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
workspaceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

localHeads(index: number):string
localHeads(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
localHeads(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

localHeadsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSyncRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addWorkspaceId(builder:flatbuffers.Builder, workspaceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, workspaceIdOffset, 0);
}

static addLocalHeads(builder:flatbuffers.Builder, localHeadsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, localHeadsOffset, 0);
}

static createLocalHeadsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLocalHeadsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSyncRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSyncRequest(builder:flatbuffers.Builder, workspaceIdOffset:flatbuffers.Offset, localHeadsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SyncRequest.startSyncRequest(builder);
  SyncRequest.addWorkspaceId(builder, workspaceIdOffset);
  SyncRequest.addLocalHeads(builder, localHeadsOffset);
  return SyncRequest.endSyncRequest(builder);
}

unpack(): SyncRequestT {
  return new SyncRequestT(
    this.workspaceId(),
    this.bb!.createScalarList<string>(this.localHeads.bind(this), this.localHeadsLength())
  );
}


unpackTo(_o: SyncRequestT): void {
  _o.workspaceId = this.workspaceId();
  _o.localHeads = this.bb!.createScalarList<string>(this.localHeads.bind(this), this.localHeadsLength());
}
}

export class SyncRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public workspaceId: string|Uint8Array|null = null,
  public localHeads: (string)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const workspaceId = (this.workspaceId !== null ? builder.createString(this.workspaceId!) : 0);
  const localHeads = SyncRequest.createLocalHeadsVector(builder, builder.createObjectOffsetList(this.localHeads));

  return SyncRequest.createSyncRequest(builder,
    workspaceId,
    localHeads
  );
}
}
