// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MsgType } from '../nmeshed/msg-type.js';
import { Op, OpT } from '../nmeshed/op.js';
import { Signal, SignalT } from '../nmeshed/signal.js';
import { SyncPacket, SyncPacketT } from '../nmeshed/sync-packet.js';


export class WirePacket implements flatbuffers.IUnpackableObject<WirePacketT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WirePacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWirePacket(bb:flatbuffers.ByteBuffer, obj?:WirePacket):WirePacket {
  return (obj || new WirePacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWirePacket(bb:flatbuffers.ByteBuffer, obj?:WirePacket):WirePacket {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WirePacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

msgType():MsgType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MsgType.Unknown;
}

op(obj?:Op):Op|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Op()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

payload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

payloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

payloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

signal(obj?:Signal):Signal|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Signal()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

sync(obj?:SyncPacket):SyncPacket|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new SyncPacket()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startWirePacket(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addMsgType(builder:flatbuffers.Builder, msgType:MsgType) {
  builder.addFieldInt8(0, msgType, MsgType.Unknown);
}

static addOp(builder:flatbuffers.Builder, opOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, opOffset, 0);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, payloadOffset, 0);
}

static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addSignal(builder:flatbuffers.Builder, signalOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, signalOffset, 0);
}

static addSync(builder:flatbuffers.Builder, syncOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, syncOffset, 0);
}

static endWirePacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishWirePacketBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedWirePacketBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}


unpack(): WirePacketT {
  return new WirePacketT(
    this.msgType(),
    (this.op() !== null ? this.op()!.unpack() : null),
    this.bb!.createScalarList<number>(this.payload.bind(this), this.payloadLength()),
    (this.signal() !== null ? this.signal()!.unpack() : null),
    (this.sync() !== null ? this.sync()!.unpack() : null)
  );
}


unpackTo(_o: WirePacketT): void {
  _o.msgType = this.msgType();
  _o.op = (this.op() !== null ? this.op()!.unpack() : null);
  _o.payload = this.bb!.createScalarList<number>(this.payload.bind(this), this.payloadLength());
  _o.signal = (this.signal() !== null ? this.signal()!.unpack() : null);
  _o.sync = (this.sync() !== null ? this.sync()!.unpack() : null);
}
}

export class WirePacketT implements flatbuffers.IGeneratedObject {
constructor(
  public msgType: MsgType = MsgType.Unknown,
  public op: OpT|null = null,
  public payload: (number)[] = [],
  public signal: SignalT|null = null,
  public sync: SyncPacketT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const op = (this.op !== null ? this.op!.pack(builder) : 0);
  const payload = WirePacket.createPayloadVector(builder, this.payload);
  const signal = (this.signal !== null ? this.signal!.pack(builder) : 0);
  const sync = (this.sync !== null ? this.sync!.pack(builder) : 0);

  WirePacket.startWirePacket(builder);
  WirePacket.addMsgType(builder, this.msgType);
  WirePacket.addOp(builder, op);
  WirePacket.addPayload(builder, payload);
  WirePacket.addSignal(builder, signal);
  WirePacket.addSync(builder, sync);

  return WirePacket.endWirePacket(builder);
}
}
