// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ActorRegistry } from '../nmeshed/actor-registry.js';
import { ColumnarOpBatch } from '../nmeshed/columnar-op-batch.js';
import { CompareAndSwap } from '../nmeshed/compare-and-swap.js';
import { MsgType } from '../nmeshed/msg-type.js';
import { Op } from '../nmeshed/op.js';
import { Signal } from '../nmeshed/signal.js';
import { Snapshot } from '../nmeshed/snapshot.js';
import { SyncPacket } from '../nmeshed/sync-packet.js';


export class WirePacket {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WirePacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWirePacket(bb:flatbuffers.ByteBuffer, obj?:WirePacket):WirePacket {
  return (obj || new WirePacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWirePacket(bb:flatbuffers.ByteBuffer, obj?:WirePacket):WirePacket {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WirePacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

msgType():MsgType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MsgType.Unknown;
}

op(obj?:Op):Op|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Op()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

payload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

payloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

payloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

signal(obj?:Signal):Signal|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Signal()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

timestamp():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

sync(obj?:SyncPacket):SyncPacket|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new SyncPacket()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

actorRegistry(obj?:ActorRegistry):ActorRegistry|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new ActorRegistry()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

batch(obj?:ColumnarOpBatch):ColumnarOpBatch|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new ColumnarOpBatch()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

snapshot(obj?:Snapshot):Snapshot|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new Snapshot()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

cas(obj?:CompareAndSwap):CompareAndSwap|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new CompareAndSwap()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startWirePacket(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addMsgType(builder:flatbuffers.Builder, msgType:MsgType) {
  builder.addFieldInt8(0, msgType, MsgType.Unknown);
}

static addOp(builder:flatbuffers.Builder, opOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, opOffset, 0);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, payloadOffset, 0);
}

static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addSignal(builder:flatbuffers.Builder, signalOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, signalOffset, 0);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:number) {
  builder.addFieldFloat64(4, timestamp, 0.0);
}

static addSync(builder:flatbuffers.Builder, syncOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, syncOffset, 0);
}

static addActorRegistry(builder:flatbuffers.Builder, actorRegistryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, actorRegistryOffset, 0);
}

static addBatch(builder:flatbuffers.Builder, batchOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, batchOffset, 0);
}

static addSnapshot(builder:flatbuffers.Builder, snapshotOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, snapshotOffset, 0);
}

static addCas(builder:flatbuffers.Builder, casOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, casOffset, 0);
}

static endWirePacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishWirePacketBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedWirePacketBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

}
