const fs = require('fs');
const coverage = JSON.parse(fs.readFileSync('coverage/coverage-final.json', 'utf8'));

let totalStmts = 0;
let coveredStmts = 0;
let totalBranches = 0;
let coveredBranches = 0;

for (const [file, data] of Object.entries(coverage)) {
    if (file.includes('schema/nmeshed') || file.includes('wasm/nmeshed_core.js')) {
        continue;
    }

    const s = data.s;
    for (const count of Object.values(s)) {
        totalStmts++;
        if (count > 0) coveredStmts++;
    }

    const b = data.b;
    for (const counts of Object.values(b)) {
        for (const count of counts) {
            totalBranches++;
            if (count > 0) coveredBranches++;
        }
    }
}

const stmtPercentage = (coveredStmts / totalStmts * 100).toFixed(2);
const branchPercentage = (coveredBranches / totalBranches * 100).toFixed(2);
console.log(`Non-autogenerated Statement Coverage: ${stmtPercentage}% (${coveredStmts}/${totalStmts})`);
console.log(`Non-autogenerated Branch Coverage: ${branchPercentage}% (${coveredBranches}/${totalBranches})`);
