// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { Answer } from '../nmeshed/answer.js';
import { Candidate } from '../nmeshed/candidate.js';
import { Join } from '../nmeshed/join.js';
import { Offer } from '../nmeshed/offer.js';
import { Relay } from '../nmeshed/relay.js';


export enum SignalData {
  NONE = 0,
  Join = 1,
  Offer = 2,
  Answer = 3,
  Candidate = 4,
  Relay = 5
}

export function unionToSignalData(
  type: SignalData,
  accessor: (obj:Answer|Candidate|Join|Offer|Relay) => Answer|Candidate|Join|Offer|Relay|null
): Answer|Candidate|Join|Offer|Relay|null {
  switch(SignalData[type]) {
    case 'NONE': return null; 
    case 'Join': return accessor(new Join())! as Join;
    case 'Offer': return accessor(new Offer())! as Offer;
    case 'Answer': return accessor(new Answer())! as Answer;
    case 'Candidate': return accessor(new Candidate())! as Candidate;
    case 'Relay': return accessor(new Relay())! as Relay;
    default: return null;
  }
}

export function unionListToSignalData(
  type: SignalData, 
  accessor: (index: number, obj:Answer|Candidate|Join|Offer|Relay) => Answer|Candidate|Join|Offer|Relay|null, 
  index: number
): Answer|Candidate|Join|Offer|Relay|null {
  switch(SignalData[type]) {
    case 'NONE': return null; 
    case 'Join': return accessor(index, new Join())! as Join;
    case 'Offer': return accessor(index, new Offer())! as Offer;
    case 'Answer': return accessor(index, new Answer())! as Answer;
    case 'Candidate': return accessor(index, new Candidate())! as Candidate;
    case 'Relay': return accessor(index, new Relay())! as Relay;
    default: return null;
  }
}
